
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kubevip-cp-talk-to-apiserver
  namespace: {{ .Release.Namespace | default "kube-system" }}
spec:
  podSelector:
    {{- include "kube-vip-cloud-provider.selectorLabels" . | nindent 4 }}
  policyTypes:
    - Egress
  egress:
  - ports:
    - port: 443
      protocol: TCP
    - port: 6443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 0.0.0.0/0
---
apiVersion: networking.k8s.io/v1
kind: CiliumNetworkPolicy
metadata:
  name: allow-kubevip-cp-talk-to-apiserver
  namespace: {{ .Release.Namespace | default "kube-system" }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "kube-vip-cloud-provider.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - toEntities:
      - kube-apiserver
---
