apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: helm/kube-vip-cloud-provider-app
  contents:
  - path: .
    git:
      url: https://github.com/kube-vip/helm-charts
      ref: kube-vip-cloud-provider-0.2.2
      depth: 1
    newRootPath: charts/kube-vip-cloud-provider
    ignorePaths:
    - Chart.yaml
    - _gs-helpers.tpl
