apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: kube-vip-cloud-provider
        git:
          depth: 1
          url: https://github.com/kube-vip/helm-charts
          ref: "kube-vip-cloud-provider-0.2.5"
        includePaths:
          - charts/kube-vip-cloud-provider/**/*
  - path: helm
    contents:
    - path: .
      directory:
        path: vendor/kube-vip-cloud-provider/charts/
      ignorePaths:
        - kube-vip-cloud-provider/templates/npols.yaml
        - kube-vip/templates/policyexception.yaml
        - kube-vip/values.schema.json
