
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kubevip-cp-talk-to-apiserver
  namespace: {{ .Release.Namespace | default "kube-system" }}
  labels:
    {{- include "kube-vip-cloud-provider.labels" $ | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "kube-vip-cloud-provider.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
  - ports:
    - port: 443
      protocol: TCP
    - port: 6443
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          component: kube-apiserver
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-kubevip-cp-talk-to-apiserver
  namespace: {{ .Release.Namespace | default "kube-system" }}
  labels:
    {{- include "kube-vip-cloud-provider.labels" $ | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "kube-vip-cloud-provider.selectorLabels" . | nindent 6 }}
  egress:
    - toEntities:
      - kube-apiserver
      toPorts:
        - ports:
          - port: "443"
            protocol: TCP
          - port: "6443"
            protocol: TCP
---
