apiVersion: v2
appVersion: 0.0.1
# version: 0.0.1
version: [[ .Version ]]

name: kube-vip-cloud-provider

description: kube-vip-cloud-provider helm chart installs controller that assigns the free IP to a service of type LoadBalancer. It ships also the NetworkPolicies.

home: https://github.com/giantswarm/kube-vip-cloud-provider

# If you have an icon/logo, you should add it to https://github.com/giantswarm/web-assets
# and set the final URL as a value here and uncomment.
icon: https://github.com/kube-vip/kube-vip/raw/main/kube-vip.png

sources:
- https://github.com/giantswarm/kube-vip-cloud-provider
annotations:
  application.giantswarm.io/team: rocket
maintainers:
  - name: Team Rocket
    email: team-rocket@giantswarm.io
