name: check generated yamls

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  check:
    name: check generated yamls
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-ci') }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
    - name: install vendir
      uses: carvel-dev/setup-action@v2
      with:
        only: vendir
    - name: generate manifests
      run: APPLICATION=helm/kube-vip-cloud-provider make update-chart
    - name: check no change
      run: git diff --quiet --exit-code && [ -z "$(git status --porcelain)" ]
